#!/usr/bin/env python3
"""Generate the Asteroids rock outlines as Logo turtle walks.

docs/asteroids-design.md section 6.3: an outline is authored as N radii at
equal angular spacing around a centre, and this script converts that to the
walk a turtle makes -- segment lengths and exterior turns.  Hand-written
turns do not close, and an unclosed rock leaves a gap that `pe` still erases
correctly but that looks broken.

Nine outlines: three shapes x three sizes, with the scale baked into the
literals rather than computed on the board, because on hardware an arithmetic
statement costs 48 us and a literal-argument primitive call is a fraction of
that (docs/interpreter-throughput-design.md section 11).

Run it and paste the output into the Logo file:

    python3 scripts/gen_rocks.py

The walk drops the turn after the final segment -- `place` sets the heading
before every pass, so that turn is never read.  That is what makes the
statement counts 19/15/13 in the design's table.
"""

import math
import random

# Segments and radius by size, from the design's table.  Segment counts fall
# with size, which is where the saving belongs: small rocks are the numerous
# ones.
SIZES = [("l", 8, 22.0), ("m", 6, 14.0), ("s", 5, 8.0)]

SHAPES = ["a", "b", "c"]

# Radii vary between these fractions of the nominal radius.  The floor is high
# enough that the polygon stays star-shaped and roughly convex at every
# segment count, so the walk has no reflex vertex to turn back through.
JITTER = (0.74, 1.0)


def vertices(n, radius, rng):
    """N points at equal angular spacing, at jittered radii.

    Logo headings are clockwise from north, so a bearing t maps to
    (sin t, cos t) and vertex 0 sits straight ahead of a turtle at heading 0 --
    which is what lets the walk's prologue be a single `fd`.
    """
    pts = []
    for k in range(n):
        t = math.radians(k * 360.0 / n)
        r = radius * rng.uniform(*JITTER)
        pts.append((r * math.sin(t), r * math.cos(t)))
    return pts


def bearing(a, b):
    """Logo heading, in degrees, that walks from point a to point b."""
    return math.degrees(math.atan2(b[0] - a[0], b[1] - a[1])) % 360.0


def turn_to(current, wanted):
    """Signed turn from one heading to another, in (-180, 180]."""
    d = (wanted - current) % 360.0
    return d - 360.0 if d > 180.0 else d


def walk(pts):
    """The turtle walk for a closed polygon: (prologue, [(len, turn), ...]).

    Every number is rounded to one decimal.  That is still one literal token,
    so it costs exactly what an integer costs to evaluate, and it holds the
    closure error under half a pixel -- integer turns alone would drift by
    two or three across eight segments.
    """
    n = len(pts)
    reach = round(math.hypot(*pts[0]), 1)
    heading = 0.0
    first_turn = round(turn_to(heading, bearing(pts[0], pts[1])), 1)
    heading += first_turn

    legs = []
    for k in range(n):
        a, b = pts[k], pts[(k + 1) % n]
        length = round(math.hypot(b[0] - a[0], b[1] - a[1]), 1)
        if k == n - 1:
            legs.append((length, None))  # no turn after the last segment
            break
        wanted = bearing(b, pts[(k + 2) % n])
        t = round(turn_to(heading, wanted), 1)
        heading += t
        legs.append((length, t))
    return reach, first_turn, legs


def closure_error(pts, reach, first_turn, legs):
    """How far the *emitted* walk lands from where it started, in pixels."""
    x = y = 0.0
    heading = 0.0
    x += reach * math.sin(math.radians(heading))
    y += reach * math.cos(math.radians(heading))
    start = (x, y)
    heading += first_turn
    for length, t in legs:
        x += length * math.sin(math.radians(heading))
        y += length * math.cos(math.radians(heading))
        if t is not None:
            heading += t
    return math.hypot(x - start[0], y - start[1])


def fmt(v):
    """Trim a trailing `.0` so the common case reads as an integer."""
    return f"{v:g}"


def step(kind, value):
    if value < 0:
        return f"{'lt' if kind == 'rt' else 'rt'} {fmt(-value)}"
    return f"{kind} {fmt(value)}"


def emit(shape, size, n, radius, rng):
    pts = vertices(n, radius, rng)
    reach, first_turn, legs = walk(pts)
    err = closure_error(pts, reach, first_turn, legs)

    body = []
    for length, t in legs:
        body.append(f"fd {fmt(length)}" + ("" if t is None else f"  {step('rt', t)}"))

    lines = [f"to rock.{shape}.{size}"]
    lines.append(f"  pu fd {fmt(reach)}  {step('rt', first_turn)}  pd")
    for i in range(0, len(body), 4):
        lines.append("  " + "  ".join(body[i:i + 4]))
    lines.append("end")

    statements = 4 + (2 * n - 1)
    return "\n".join(lines), err, statements


def main():
    print("; Generated by scripts/gen_rocks.py -- do not hand-edit.")
    print("; Outlines close to within a pixel; see the design section 6.3.")
    for shape in SHAPES:
        for size, n, radius in SIZES:
            # Seeded per outline so a regeneration reproduces the file exactly.
            rng = random.Random(f"{shape}{size}")
            text, err, statements = emit(shape, size, n, radius, rng)
            print()
            print(f"; {n} segments, {statements} statements, "
                  f"closes to {err:.2f} px")
            print(text)


if __name__ == "__main__":
    main()
